- name: Установка пакетов NFS
  dnf:
    name: nfs-utils
    state: present

- name: Настройка конфигурации экспорта NFS
  copy:
    src: ../templates/exports
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify:
    - Перезапуск NFS

- name: Перезапуск NFS
  service:
    name: nfs-utils
    state: restarted

