- name: Обновление dnf и установка основных утилит
  dnf:
    update_cache: yes
    name:
      - vim
      - curl
      - htop
      - rsync
      - firewalld
    state: present

- name: Создание группы fileshare
  group:
    name: fileshare
    state: present

- name: Создание общей директории хранения
  file:
    path: /srv/storage
    state: directory
    owner: nobody
    group: nobody
    mode: '0777'


- name: Добавление пользователей
  loop: "{{ users }}"
  user:
    name: "{{ item.name }}"
    groups: [fileshare]
    append: yes
    shell: /bin/bash
    state: present
